const data = {
    products:[
        {
            _id: '1',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image:'images/p2.jpg',
            price:120,
            countInStock: 10,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'high quality material',
        },
        {
            _id: '2',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image:'../images/p1.jpg',
            price:520,
            countInStock: 20,
            brand:'Nike',
            rating:4.5,
            numReviews:20,
            description:'high quality material',
        },
        {
            _id: '3',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image:'../images/p1.jpg',
            price:395,
            countInStock: 0,
            brand:'Nike',
            rating:4.5,
            numReviews:0,
            description:'high quality material',
        },
        {
            _id: '4',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image:'../images/p1.jpg',
            price:230,
            countInStock: 15,
            brand:'Nike',
            rating:4.5,
            numReviews:15,
            description:'high quality material',
        },
        {
            _id: '5',
            name: 'Pants Slim Shirt',
            category: 'Pants',
            image:'../images/p1.jpg',
            price:650,
            countInStock: 4,
            brand:'puma',
            rating:3.5,
            numReviews:4,
            description:'high quality material',
        },
        {
            _id: '6',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image:'../images/p1.jpg',
            price:120,
            countInStock: 16,
            brand:'Nike',
            rating:4.5,
            numReviews:16,
            description:'high quality material',
        },
    ],
};
export default data;