const data = {
    products:[
        {
            _id: '1',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image:'/images/p1.jpg',
            price:120,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'high quality material',
        },
        {
            _id: '2',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image:'/images/p1.jpg',
            price:520,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'high quality material',
        },
        {
            _id: '3',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image:'/images/p1.jpg',
            price:395,
            brand:'Nike',
            rating:4.5,
            numReviews:16,
            description:'high quality material',
        },
        {
            _id: '4',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image:'/images/p1.jpg',
            price:230,
            brand:'Nike',
            rating:4.5,
            numReviews:50,
            description:'high quality material',
        },
        {
            _id: '5',
            name: 'Pants Slim Shirt',
            category: 'Pants',
            image:'/images/p1.jpg',
            price:650,
            brand:'puma',
            rating:3.5,
            numReviews:45,
            description:'high quality material',
        },
        {
            _id: '6',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image:'/images/p1.jpg',
            price:120,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'high quality material',
        },
    ],
};
export default data;